collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "authors"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll_picture_tag

excerpt_separator: <!--more-->
incremental: false

paginate: 10
paginate_path: "page:num/"

sass:
    style: compressed

include: [".nojekyll"]

url: https://ifthehuefits.github.io/

picture:
    source: "assets/images"
    output: "generated/images"
    suppress_warnings: true
